// GENERATED BY HAND FOR SIMPLICITY
part of 'fillup.dart';

class FillUpAdapter extends TypeAdapter<FillUp> {
  @override
  final int typeId = 2;

  @override
  FillUp read(BinaryReader reader) {
    final n = reader.readByte();
    final f = <int, dynamic>{};
    for (var i = 0; i < n; i++) { f[reader.readByte()] = reader.read(); }
    return FillUp(
      id: f[0] as String,
      vehicleId: f[1] as String,
      odometer: f[2] as double,
      fuelVolume: f[3] as double,
      pricePaid: f[4] as double,
      date: f[5] as DateTime,
      unitSystem: f[6] as String,
      isFullTank: f[7] as bool? ?? true,
    );
  }

  @override
  void write(BinaryWriter w, FillUp obj) {
    w
      ..writeByte(8)
      ..writeByte(0)..write(obj.id)
      ..writeByte(1)..write(obj.vehicleId)
      ..writeByte(2)..write(obj.odometer)
      ..writeByte(3)..write(obj.fuelVolume)
      ..writeByte(4)..write(obj.pricePaid)
      ..writeByte(5)..write(obj.date)
      ..writeByte(6)..write(obj.unitSystem)
      ..writeByte(7)..write(obj.isFullTank);
  }
}
