// GENERATED BY HAND FOR SIMPLICITY
part of 'reminder.dart';

class VehicleReminderAdapter extends TypeAdapter<VehicleReminder> {
  @override
  final int typeId = 3;

  @override
  VehicleReminder read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (var i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return VehicleReminder(
      typeIndex: fields[0] as int,
      doesNotApply: fields[1] as bool? ?? false,
      dueDate: fields[2] as DateTime?,
      renewalPeriodMonths: fields[3] as int? ?? 12,
      remindDaysPrior: fields[4] as int? ?? 30,
    );
  }

  @override
  void write(BinaryWriter writer, VehicleReminder obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)..write(obj.typeIndex)
      ..writeByte(1)..write(obj.doesNotApply)
      ..writeByte(2)..write(obj.dueDate)
      ..writeByte(3)..write(obj.renewalPeriodMonths)
      ..writeByte(4)..write(obj.remindDaysPrior);
  }
}
