// GENERATED BY HAND FOR SIMPLICITY
part of 'vehicle.dart';

class VehicleAdapter extends TypeAdapter<Vehicle> {
  @override
  final int typeId = 1;

  @override
  Vehicle read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (var i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return Vehicle(
      id: fields[0] as String,
      color: fields[1] as String,
      year: fields[2] as int,
      make: fields[3] as String,
      model: fields[4] as String,
      trim: fields[5] as String,
      photoPath: fields[6] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, Vehicle obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)..write(obj.id)
      ..writeByte(1)..write(obj.color)
      ..writeByte(2)..write(obj.year)
      ..writeByte(3)..write(obj.make)
      ..writeByte(4)..write(obj.model)
      ..writeByte(5)..write(obj.trim)
      ..writeByte(6)..write(obj.photoPath);
  }
}
